from dataclasses import asdict, dataclass


@dataclass
class ColumnsBaseDTO:
    create_at: str = 'Дата создания'
    returned_at: str = 'Дата возврата'
    order_date: str = 'Заказ.Дата'
    returned_date: str = 'Документ возврата.Дата'
    order: str = 'Заказ'
    order_is_canceled: str = 'Заказ отменен'
    doc_sale: str = 'Документ продажи'
    doc_return: str = 'Документ возврата'
    order_id: str = 'Заказ.Номер'
    status: str = 'Текущий статус'
    cost_of_good: str = 'Стоимость товара'
    cost_of_delivery: str = 'Ссылка.Стоимость доставки'
    order_source: str = 'Источник заказа'
    sender_warehouse: str = 'Склад отправитель'
    posting_number: str = 'Ссылка.Номер отправления'
    cost_of_return: str = 'Сумма возврата'
    nomenclature: str = 'Номенклатура'
    article: str = 'Номенклатура.Артикул'
    characteristic_nomenclature: str = 'Характеристика номенклатуры'
    price: str = 'Цена'
    quantity: str = 'Количество'
    order_sum: str = 'Сумма заказа'
    sale_sum: str = 'Сумма продажи'
    return_sum: str = 'Сумма возврата'
    main_cost_of_sale: str = 'Себестоимость продажи'
    rrc_sale_sum: str = 'Сумма РРЦПродажи'
    main_cost_of_return: str = 'Себестоимость возврата'
    rrc_return_sum: str = 'Сумма РРЦВозврата'
    delivery_method: str = 'Заказ.Способ доставки'
    receiver_warehouse: str = 'Перемещение.Склад получатель'
    source: str = 'Заказ.Источник'
    project: str = 'Заказ.Проект'
    brand: str = 'Бренд'
    canal: str = 'Заказ.Канал'
    payment_method: str = 'Заказ.Способ оплаты'

